name: Hedge System Version Bump

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  version-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Bump version
        run: |
          cd apps/hedge-system
          npm version ${{ github.event.inputs.version_type }} --no-git-tag-version
          NEW_VERSION=$(node -pe "require('./package.json').version")
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update Tauri config version
        run: |
          cd apps/hedge-system/src-tauri
          # Update version in tauri.conf.json
          sed -i.bak "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" tauri.conf.json
          rm tauri.conf.json.bak

      - name: Commit version bump
        run: |
          git add apps/hedge-system/package.json apps/hedge-system/src-tauri/tauri.conf.json
          git commit -m "Bump hedge-system version to v$NEW_VERSION"
          git push origin main

      - name: Create and push tag
        run: |
          git tag "hedge-system-v$NEW_VERSION"
          git push origin "hedge-system-v$NEW_VERSION"